#!/bin/bash
# ~/beo/scripts/generate_litellm_config.sh
# Reads GEMINI_KEY_N from .env (any indices, non-sequential), generates litellm_config.yaml
# Run: bash ~/beo/scripts/generate_litellm_config.sh

set -euo pipefail

ENV_FILE=~/openclaw/.env
CONFIG_OUT=/root/openclaw/litellm_config.yaml

# ── Collect all GEMINI_KEY_N indices present, sorted numerically ──────────────
INDICES=()
while IFS= read -r line; do
  varname=$(echo "$line" | cut -d= -f1)
  idx=${varname#GEMINI_KEY_}
  INDICES+=("$idx")
done < <(grep -E "^GEMINI_KEY_[0-9]+=" "$ENV_FILE" | sort -t_ -k3 -n)

if [[ ${#INDICES[@]} -eq 0 ]]; then
  echo "❌ No valid GEMINI_KEY_N entries found in $ENV_FILE"
  exit 1
fi

FIRST_IDX="${INDICES[0]}"

# ── Emit one model entry per Gemini key index ─────────────────────────────────
emit_entries() {
  local model_name=$1
  local model=$2
  local extra_yaml=$3
  local extra_params=${4:-""}

  for idx in "${INDICES[@]}"; do
    cat << ENTRY
  - model_name: ${model_name}
    litellm_params:
      model: ${model}
      api_key: "os.environ/GEMINI_KEY_${idx}"${extra_params}
    model_info:
${extra_yaml}
ENTRY
  done
}

# ── Generate config ───────────────────────────────────────────────────────────
cat > "$CONFIG_OUT" << YAML
# ════════════════════════════════════════════════
# BEO — LiteLLM Configuration
# AUTO-GENERATED by ~/beo/scripts/generate_litellm_config.sh
# Do not hand-edit — re-run script to regenerate
# Generated: $(date)
# Keys loaded: ${#INDICES[@]} (${INDICES[*]/#/GEMINI_KEY_})
# ════════════════════════════════════════════════

general_settings:
  master_key: "\${LITELLM_MASTER_KEY}"
  allow_requests_on_db_unavailable: true

litellm_settings:
  cache: true
  cache_params:
    type: "redis-semantic"
    redis_url: "redis://redis:6379"
    similarity_threshold: 0.80          
    redis_semantic_cache_embedding_model: "gemini/gemini-embedding-001"
    ttl: 86400                          # 24h — prevents stale entries forever
  no_cache_for_model:                   # high entropy
    - "tier-1-brain"                    
    - "tier-3-field"                    
    - "tier-4-extraction"               
    - "tier-5-vip"        

router_settings:
  router_strategy: least-busy
  num_retries: 2
  retry_policy:
    AuthenticationErrorRetries: 0
    RateLimitErrorRetries: 3
    TimeoutErrorRetries: 2
  allowed_fails: 3
  cooldown_time: 60
  fallbacks:
    # ── Tier Emergency for Gemini, fallback to OpenRouter ──
    - tier-1-brain:
        - tier-emergency-openrouter
    - tier-2-desk:
        - tier-emergency-openrouter
    - tier-3-field:
        - tier-emergency-openrouter
    - tier-4-extraction:
        - tier-emergency-openrouter
    - tier-nano-router:
        - tier-emergency-openrouter
    # ── Tier Emergency for OpenRouter, fallback to Gemini ──
    - tier-5-vip:
        - tier-emergency-gemini

model_list:

  # ── Tier 1 — Brain (Gemini) ──
$(emit_entries "tier-1-brain" "gemini/gemini-2.5-flash" \
"      max_tokens: 1000000" \
"
      thinking:
        type: disabled")

  # ── Tier 2 — Desk (Gemini) ──
$(emit_entries "tier-2-desk" "gemini/gemini-2.5-flash" \
"      max_tokens: 1000000
      timeout: 30" \
"
      thinking:
        type: disabled")

  # ── Tier 3 — Field (Gemini) ──
$(emit_entries "tier-3-field" "gemini/gemini-2.5-flash" \
"      max_tokens: 1000000
      timeout: 90
      max_parallel_requests: 5" \
"
      thinking:
        type: disabled")

  # ── Tier 4 — Oracle / Extraction (Gemini) ──
$(emit_entries "tier-4-extraction" "gemini/gemini-2.5-pro" \
"      max_tokens: 1000000
      timeout: 300")

  # ── Tier 5 — VIP (OpenRouter Opus) ──
  - model_name: tier-5-vip
    litellm_params:
      model: openrouter/anthropic/claude-opus-4
      api_key: "\${OPENROUTER_API_KEY}"
      api_base: "https://openrouter.ai/api/v1"
      timeout: 300
    model_info:
      max_tokens: 200000

  # ── Unncapped Gemini embedding model for semantic cache ──
  - model_name: gemini-embedding-vip
    litellm_params:
      model: gemini/gemini-embedding-001
      api_key: "os.environ/GEMINI_KEY_VIP"
    model_info:
      mode: embedding

  # ── Tier Emergency for Gemini, fallback to OpenRouter ──
  - model_name: tier-emergency-openrouter
    litellm_params:
      model: openrouter/mistralai/mistral-small-3.2-24b-instruct
      api_key: "os.environ/OPENROUTER_API_KEY"
      api_base: "https://openrouter.ai/api/v1"
      timeout: 30
    model_info:
      max_tokens: 8192

  # ── Tier Emergency for OpenRouter, fallback to Gemini ──
$(emit_entries "tier-emergency-gemini" "gemini/gemini-2.5-flash-lite" \
"      max_tokens: 8192" \
"
    thinking:
      type: disabled")

  # ── Tier Nano-router (Gemini) ──
$(emit_entries "tier-nano-router" "gemini/gemini-2.5-flash-lite" \
"      max_tokens: 2048" \
"
    thinking:
      type: disabled")





YAML

# ── Strip any tab characters YAML forbids ─────────────────────────────────────
sed -i 's/\t/  /g' "$CONFIG_OUT"

echo "✅ litellm_config.yaml generated with ${#INDICES[@]} Gemini key(s): ${INDICES[*]/#/GEMINI_KEY_}"
