#!/bin/bash
# ~/beo/scripts/util_litellm_rebuild.sh
# Reads GEMINI_KEY_N from .env (any indices, non-sequential), generates litellm_config.yaml
# Run: bash ~/beo/scripts/util_litellm_rebuild.sh

set -euo pipefail

ENV_FILE=~/openclaw/.env
CONFIG_OUT=/root/openclaw/litellm_config.yaml
SUMMARY_OUTPUT=""

# ── Collect all GEMINI_KEY_N indices present, sorted numerically ──────────────
INDICES=()
while IFS= read -r line; do
  varname=$(echo "$line" | cut -d= -f1)
  idx=${varname#GEMINI_KEY_}
  INDICES+=("$idx")
done < <(grep -E "^GEMINI_KEY_[0-9]+=" "$ENV_FILE" | sort -t_ -k3 -n)

if [[ ${#INDICES[@]} -eq 0 ]]; then
  echo "❌ [ERROR] No valid GEMINI_KEY_N entries found in $ENV_FILE"
  exit 1
fi

# ── Dynamic Model Emitters ────────────────────────────────────────────────────

emit_entries() {
  local model_name=$1
  local model=$2
  local extra_yaml=$3
  local label=${4:-$model_name}
  local url=${5:-""}
  local think_tag=${6:-"(💭 Thinking )"}

  local api_base_yaml=""
  if [[ -n "$url" ]]; then
    api_base_yaml="      api_base: \"$url\""
  fi

  # 36 chars perfectly fits the longest model name without the URL stretching it
  local line_out
  printf -v line_out "   ├─ %s : %-36s %s\n" "$label" "$model" "$think_tag"
  SUMMARY_OUTPUT+="$line_out"

  for idx in "${INDICES[@]}"; do
    cat << ENTRY
  - model_name: ${model_name}
    litellm_params:
      model: ${model}
      api_key: "os.environ/GEMINI_KEY_${idx}"
ENTRY
    if [[ -n "$api_base_yaml" ]]; then
      echo "$api_base_yaml"
    fi
    cat << ENTRY
    model_info:
${extra_yaml}
ENTRY
  done
}

emit_entries_no_think() {
  local model_name=$1
  local model=$2
  local extra_yaml=$3
  local label=${4:-$model_name}
  local url=${5:-""}
  local think_tag=${6:-""} 

  local api_base_yaml=""
  if [[ -n "$url" ]]; then
    api_base_yaml="      api_base: \"$url\""
  fi

  local line_out
  printf -v line_out "   ├─ %s : %-36s %s\n" "$label" "$model" "$think_tag"
  SUMMARY_OUTPUT+="$line_out"

  for idx in "${INDICES[@]}"; do
    cat << ENTRY
  - model_name: ${model_name}
    litellm_params:
      model: ${model}
      api_key: "os.environ/GEMINI_KEY_${idx}"
ENTRY
    if [[ -n "$api_base_yaml" ]]; then
      echo "$api_base_yaml"
    fi
    cat << ENTRY
      thinking:
        type: disabled
        thinkingBudget: 0
    model_info:
${extra_yaml}
ENTRY
  done
}

emit_single_entry() {
  local model_name=$1
  local model=$2
  local api_key=$3
  local extra_yaml=$4
  local label=${5:-$model_name}
  local url=${6:-""}
  local think_tag=${7:-""} 

  local api_base_yaml=""
  if [[ -n "$url" ]]; then
    api_base_yaml="      api_base: \"$url\""
  fi

  local line_out
  printf -v line_out "   ├─ %s : %-36s %s\n" "$label" "$model" "$think_tag"
  SUMMARY_OUTPUT+="$line_out"

  cat << ENTRY
  - model_name: ${model_name}
    litellm_params:
      model: ${model}
      api_key: "${api_key}"
ENTRY
  if [[ -n "$api_base_yaml" ]]; then
    echo "$api_base_yaml"
  fi
  cat << ENTRY
    model_info:
${extra_yaml}
ENTRY
}

# ── Generate Config Header ────────────────────────────────────────────────────
cat > "$CONFIG_OUT" << YAML
# ════════════════════════════════════════════════
# BEO — LiteLLM Configuration
# AUTO-GENERATED by ~/beo/scripts/util_litellm_rebuild.sh
# Do not hand-edit — re-run script to regenerate
# Generated: $(date)
# Keys loaded: ${#INDICES[@]} (${INDICES[*]/#/GEMINI_KEY_})
# ════════════════════════════════════════════════

general_settings:
  master_key: "\${LITELLM_MASTER_KEY}"
  allow_requests_on_db_unavailable: true

litellm_settings:
  cache: true
  cache_params:
    type: "redis"
    url: "redis://beo-redis:6379" # <--- THIS LINE WAS UPDATED
  no_cache_for_model:
    - "tier-4-extraction"
    - "tier-5-vip"
  drop_params: true

router_settings:
  router_strategy: least-busy
  num_retries: 3
  retry_policy:
    AuthenticationErrorRetries: 0
    RateLimitErrorRetries: 3
    TimeoutErrorRetries: 3
    ServiceUnavailableErrorRetries: 3
  allowed_fails: 5
  cooldown_time: 30
  fallbacks:
    - tier-5-vip:
        - tier-emergency-gemini

model_list:
YAML

# ── Generate Model Entries ────────────────────────────────────────────────────
{
  emit_entries_no_think "tier-1-brain" "gemini/gemini-2.5-flash" \
"      max_tokens: 1000000" \
  "🧠  Tier 1 (Brain)      "

  emit_entries_no_think "tier-2-desk" "gemini/gemini-2.5-flash" \
"      max_tokens: 1000000
      timeout: 30" \
  "🗂️   Tier 2 (Desk)       "

  emit_entries_no_think "tier-3-field" "gemini/gemini-2.5-flash-lite" \
"      max_tokens: 1000000
      timeout: 90
      max_parallel_requests: 5" \
  "🗺️   Tier 3 (Field)      "

  emit_entries "tier-4-extraction" "gemini/gemini-2.5-pro" \
"      max_tokens: 1000000
      timeout: 300" \
  "🌀  Tier 4 (Oracle)     "

  emit_single_entry "tier-5-vip" "openrouter/anthropic/claude-opus-4" "\${OPENROUTER_API_KEY}" \
"      max_tokens: 200000
      timeout: 300" \
  "👑  Tier 5 (VIP)        " \
  "https://openrouter.ai/api/v1" \
  "(💭 Thinking )"

  emit_single_entry "gemini-embedding-vip" "gemini/gemini-embedding-001" "os.environ/GEMINI_KEY_VIP" \
"      mode: embedding" \
  "🎩  Embed VIP           "

  emit_single_entry "tier-embedding" "gemini/gemini-embedding-001" "os.environ/GEMINI_KEY_1" \
"      mode: embedding" \
  "🗄️   Tier Embedding      "

  emit_entries_no_think "tier-emergency-gemini" "gemini/gemini-2.5-flash-lite" \
"      max_tokens: 8192" \
  "🚑  Tier Emergency      "

  emit_entries_no_think "tier-nano" "gemini/gemini-2.5-flash-lite" \
"      max_tokens: 2048" \
  "⏱️   Tier Nano           "
  
} >> "$CONFIG_OUT"

# ── Final Cleanup & Formatting ────────────────────────────────────────────────
sed -i 's/\t/  /g' "$CONFIG_OUT"
SUMMARY_OUTPUT="${SUMMARY_OUTPUT%├─*}└─${SUMMARY_OUTPUT##*├─}"

echo ""
echo "✨ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ✨"
echo "🚀  LiteLLM Configuration Rebuild Complete!   🚀"
echo "✨ ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ ✨"
echo ""
echo " 📁 Destination : $CONFIG_OUT"
echo ""
echo " 🔑 Dynamic Keys Loaded : ${#INDICES[@]} total (${INDICES[*]/#/GEMINI_KEY_})"
echo ""
echo " 🤖 Tier Mappings:"
echo "$SUMMARY_OUTPUT"
echo ""
